spring:
  datasource:
    username: ENC(mvSYFqPapKlF4pTx36IDRA==)
    password: ENC(01lZtxYjwpNYskuBlmDimtdSgBhurWMw)
    url: ENC(EIN4Jeo7kWR+xFOXEW435GagK/0CwcJ8i6xC3zYyVHoswMqaGw6+K6U62NZaLubcP/mvMFTFmnyTVipM6qXUw0dnGsWHsaeE2npWHgDmaCZErZvnJbwPqA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
jasypt:
  encryptor:
    password: ${SECRET}

